//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightWorks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCheckIn
    {
        public string UserID { get; set; }
        public System.DateTime Usertime { get; set; }
        public int EID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
